# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combined_mu', models.FloatField(blank=True, null=True)),
                ('combined_elo', models.FloatField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_a', related_query_name='player_a', to='account.Profile')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_b', related_query_name='target_b', to='account.Profile')),
            ],
        ),
    ]
