# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('pick_date', models.DateTimeField(blank=True, null=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='judges', related_query_name='judge', to='account.Profile')),
                ('left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leftProfiles', related_query_name='leftProfile', to='account.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mu', models.FloatField(blank=True, null=True)),
                ('sigma', models.FloatField(blank=True, null=True)),
                ('elo', models.FloatField(blank=True, null=True)),
                ('update_date', models.DateTimeField()),
                ('trueskill_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('elo_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_judges', related_query_name='player_judge', to='account.Profile')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', related_query_name='target', to='account.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='battle',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='losers', related_query_name='loser', to='battle.Player'),
        ),
        migrations.AddField(
            model_name='battle',
            name='right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rightProfiles', related_query_name='rightProfile', to='account.Profile'),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winners', related_query_name='winner', to='battle.Player'),
        ),
    ]
