# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-29 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='priority',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='update_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
