# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-05 04:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('battle', '0002_auto_20170729_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='data',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='left_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_battles', to='gallery.Gallery'),
        ),
        migrations.AddField(
            model_name='battle',
            name='right_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_battles', to='gallery.Gallery'),
        ),
    ]
