
# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-29 19:00
from __future__ import unicode_literals
from django.utils.text import slugify
from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    try:
        Trait = apps.get_model('account', 'Trait')
        TraitType = apps.get_model('account', 'TraitType')
    except LookupError:
        # The old app isn't installed.
        return

    traitTypes = TraitType.objects.bulk_create([
        TraitType(name="race", label="Race"),
        TraitType(name="ethnicity", label="Ethnic Identity"),
        TraitType(name="nationality", label="Nationality"),
        TraitType(name="religion", label="Religion"),
    ])
    
    ## race options
    raceType = traitTypes[0]
    Trait.objects.bulk_create([
        Trait(name="asian", label="East Asian", type=raceType),
        Trait(name="south_asian", label="South Asian", type=raceType),
        Trait(name="south_east_asian", label="South East Asian", type=raceType),
        Trait(name="caucasian", label="Caucasian / European", type=raceType),
        Trait(name="black", label="African / Black", type=raceType),
        Trait(name="middle_eastern", label="Middle Eastern", type=raceType),
        Trait(name="hispanic", label="Hispanic", type=raceType),
        Trait(name="pacific", label="Pacific Islander", type=raceType),
        Trait(name="native_american", label="Native American", type=raceType),
    ])

    ethnicityType = traitTypes[1]
    ethnicity_labels = ["Acholi", "Akan","Albanians","Afar","Afrikaners","Amhara","Arabs","Armenians","Assamese","Assyrians","Azerbaijanis","Balochis","Bamars","Bambara","Bashkirs","Basques","Belarusians","Bemba","Bengalis","Berbers","Beti-Pahuin","Bosniaks","Brahui","British","Bulgarians","Catalans","Chuvash","Circassians","Chewa","Cornish","Corsicans","Croats","Czechs","Danes","Dinka","Dutch","English","Estonians","Faroese","Finns","French","Frisians","Fula","Ga-Adangbe","Gagauz","Galician","Ganda","Germans","Greeks","Georgians","Gujarati","Hadiya","Han Chinese","Hausa","Hindustani","Hui","Hungarians","Ibibio","Icelanders","Igbo","Ijaw","Irish","Italians","Japanese","Javanese","Jews","Kannada","Karen","Kashmiris","Kazakhs","Kikuyu","Kongo","Konkani","Koreans","Kurds","Kyrgyz","Lango","Latvians","Lithuanians","Laz","Luba","Luo","Macedonians","Malays","Malayali","Maltese","Manchu","Mandinka","Marathi","Moldovans","Mongo","Mongols","Naga","Nepali","Norwegians","Nubians","Nuer","Odia","Oromo","Parsi","Pashtuns","Persians","Poles","Portuguese","Punjabi","Pedi","Romanians","Romani","Russians","Sara","Sardinians","Scottish","Serbs","Shona","Sindhis","Sinhalese","Slovaks","Slovenes","Soga","Somalis","Songhai","Soninke","Sotho","Spaniards","Sundanese","Sukuma","Swazi","Swedes","Tajiks","Tamils","Telugu","Tais","Tibetans","Tswana","Tuaregs","Turks","Turkmens","Ukrainians","Uyghur","Uzbek","Vietnamese","Volga Tatars","Welsh","Xhosa","Yakuts","Yoruba","Zhuang","Zulu"]
    trait = [Trait(name=slugify(ethnicity_label), label=ethnicity_label, type=ethnicityType) for ethnicity_label in ethnicity_labels]
    Trait.objects.bulk_create(trait)

    nationalityType = traitTypes[2]
    country_labels = ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas, The", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burma", "Burundi", "Cambodia", "Cameroon", "Canada", "Cabo Verde", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo, Democratic Republic of the", "Congo, Republic of the", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba", "Curacao", "Cyprus", "Czechia", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Timor-Leste", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia, The", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Holy See", "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Korea, North", "Korea, South", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macau", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "Norway", "Oman", "Pakistan", "Palau", "Palestinian Territories", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Sint Maarten", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Swaziland", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"]
    nationalityOptions = [Trait(name=slugify(country), label=country, type=nationalityType) for country in country_labels]
    Trait.objects.bulk_create(nationalityOptions)

    religionType = traitTypes[3]
    religion_labels = ["Catholic", "Christian", "Judaism", "Druze", "Buddhism", "Islam", "Hinduism", "Jainism", "Sikhism", "Shinto", "Taoism", "Agnostic", "Spiritual"]
    trait = [Trait(name=slugify(ethnicity_label), label=ethnicity_label, type=religionType) for ethnicity_label in ethnicity_labels]
    Trait.objects.bulk_create(trait)


class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]

    dependencies = [
        ('account', '0002_auto_20170730_1856'),
    ]