# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-27 18:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_create_traits'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(db_index=True, default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=utc))),
                ('end_date', models.DateTimeField(db_index=True, default=datetime.datetime(3000, 1, 1, 0, 0, tzinfo=utc))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(db_index=True, default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=utc))),
                ('end_date', models.DateTimeField(db_index=True, default=datetime.datetime(3000, 1, 1, 0, 0, tzinfo=utc))),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreferenceMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(db_index=True, default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=utc))),
                ('end_date', models.DateTimeField(db_index=True, default=datetime.datetime(3000, 1, 1, 0, 0, tzinfo=utc))),
                ('mutual', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegularMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(db_index=True, default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=utc))),
                ('end_date', models.DateTimeField(db_index=True, default=datetime.datetime(3000, 1, 1, 0, 0, tzinfo=utc))),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='account.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='traitidentity',
            name='end_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(3000, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='traitidentity',
            name='start_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='traitpreference',
            name='end_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(3000, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='traitpreference',
            name='start_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender_preference',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female'), (b'BI', b'Bisexual')], default=b'M', max_length=10),
        ),
        migrations.AlterField(
            model_name='traitidentity',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_identities', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='traitpreference',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
        migrations.AlterIndexTogether(
            name='traitidentity',
            index_together=set([('start_date', 'end_date')]),
        ),
        migrations.AlterIndexTogether(
            name='traitpreference',
            index_together=set([('start_date', 'end_date')]),
        ),
        migrations.AddField(
            model_name='regularmembership',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter_memberships', to='account.Profile'),
        ),
        migrations.AddField(
            model_name='regularmembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='account.Profile'),
        ),
        migrations.AddField(
            model_name='preferencematch',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='account.Profile'),
        ),
        migrations.AddField(
            model_name='preferencematch',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_matches', to='account.Profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(related_name='admin_groups', through='account.AdminMembership', to='account.Profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', through='account.RegularMembership', to='account.Profile'),
        ),
        migrations.AddField(
            model_name='adminmembership',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_memberships', to='account.Profile'),
        ),
        migrations.AddField(
            model_name='adminmembership',
            name='admin_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_group_memberships', to='account.Group'),
        ),
        migrations.AddField(
            model_name='adminmembership',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_inviter_memberships', to='account.Profile'),
        ),
        migrations.AlterIndexTogether(
            name='regularmembership',
            index_together=set([('start_date', 'end_date')]),
        ),
        migrations.AlterIndexTogether(
            name='preferencematch',
            index_together=set([('start_date', 'end_date')]),
        ),
        migrations.AlterIndexTogether(
            name='group',
            index_together=set([('start_date', 'end_date')]),
        ),
        migrations.AlterIndexTogether(
            name='adminmembership',
            index_together=set([('start_date', 'end_date')]),
        ),
    ]
