# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-29 05:40
from __future__ import unicode_literals
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170827_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='parent_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Trait'),
        ),
    ]
